name: multiarch-builds

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-${{ matrix.os }}

    timeout-minutes: 60

    strategy:
      matrix:
        file: [drone-cache]
        os: [2019]

    env:
      BASE: ${{ matrix.os }}
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}
      TAG: windows-${{ matrix.os }}

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      # ignore not yet existing images
      - name: Fetch the Docker image
        run: |
          docker pull ${{ env.IMAGE }}
          docker pull ${{ env.IMAGE }}:${{ env.TAG }}
        continue-on-error: true

      - name: Build the Docker image
        run: docker build --progress plain -t ${{ env.IMAGE }}:${{ env.TAG }} --cache-from ${{ env.IMAGE }} --cache-from ${{ env.IMAGE }}:${{ env.TAG }} ./windows/${{ env.BASE }}/${{ env.FILE }}

      - name: Test run
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./windows/${{ env.BASE }}/${{ env.FILE }}
        env:
          IMAGE: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ env.IMAGE }}:${{ env.TAG }}

  linux:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [drone-cache]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}
      TAG: linux

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: docker-config
        uses: renovatebot/internal-tools@72ddda993f900c3cf14804b1096b16cf41d44685 # tag=v1.13.5
        with:
          command: docker-config

      - name: Build the Docker image
        run: docker buildx bake --progress plain test

      - name: Test run
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./linux/${{ env.FILE }}
        env:
          IMAGE: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker buildx bake build

  multi-arch:
    needs: [linux, windows]

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    timeout-minutes: 30

    strategy:
      matrix:
        file: [drone-cache]

    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: docker-config
        uses: renovatebot/internal-tools@72ddda993f900c3cf14804b1096b16cf41d44685 # tag=v1.13.5
        with:
          command: docker-config

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build the Docker multiarch manifest
        run: docker manifest create ${{ env.IMAGE }} ${{ env.IMAGE }}:linux ${{ env.IMAGE }}:windows-2019

      - name: Publish the Docker multiarch manifest
        run: docker manifest push ${{ env.IMAGE }}

      - name: Inspect the Docker multiarch manifest
        run: docker manifest inspect ${{ env.IMAGE }}
