name: Release

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}

jobs:
  linux:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [builder, drone-server, verdaccio, rancher-cli, node, gitlab-ce, gitlab-runner, kubectl, proget, renovate, github-runner]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.2.13
        with:
          command: docker-config

      - name: Build the Docker image
        run: docker buildx bake --progress plain test

      - name: Test run
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./docker/${{ env.FILE }}

      - name: Log into registry
        if: github.ref == 'refs/heads/master'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u viceice --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/master'
        run: docker buildx bake build

      - name: Publish the Docker image tags
        if: github.ref == 'refs/heads/master'
        run: |
          if [ -f push.sh ]; then
            chmod +x ./push.sh
            ./push.sh
          fi
        working-directory: ./docker/${{ env.FILE }}

  windows:
    runs-on: windows-${{ matrix.os }}

    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        file: [builder]
        os: [2019]

    env:
      BASE: ${{ matrix.os }}
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}:windows-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build the Docker image
        run: docker build --progress plain -t ${{ env.IMAGE }} --cache-from ${{ env.IMAGE }} ./windows/${{ env.BASE }}/${{ env.FILE }}

      # - name: Test run
      #   run: docker-compose --file docker-compose.test.yml run sut
      #   working-directory: ./docker/${{ env.FILE }}

      - name: Log into registry
        if: github.ref == 'refs/heads/master'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u viceice --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/master'
        run: docker push ${{ env.IMAGE }}

      # - name: Publish the Docker image tags
      #   if: github.ref == 'refs/heads/master'
      #   run: |
      #     if [ -f push.sh ]; then
      #       chmod +x ./push.sh
      #       ./push.sh
      #     fi
      #   working-directory: ./docker/${{ env.FILE }}

  multi-arch:

    needs: [linux, windows]

    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [builder]

    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.2.13
        with:
          command: docker-config

      - name: Build the Docker multiarch manifest
        run: buildx imagetools create --append -t ${{ env.IMAGE }} ${{ env.IMAGE }}:windows-2019
