name: Test

on:
  push:
    # Run tests for any branch excerpt `master`.
    branches:
      - "**"
      - "!master"

  # Run tests for any PRs.
  pull_request:

env:
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [verdaccio, rancher-cli, node, gitlab-ce, gitlab-runner, kubectl, proget]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.1.15
        with:
          command: docker-config

      - name: Init
        run: |
          docker --version
          docker-compose --version

      - name: Build image
        run: docker buildx bake test

      - name: Test image
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./docker/${{ env.FILE }}

      - name: Image history
        run: docker history ${IMAGE}

      - name: Image size
        run: docker image ls | grep ${IMAGE}
